version: '3.5'
services:
    saml-sp:
        container_name: passport-saml-nodejs-proxy
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "3000:3000"
        restart: always
        volumes:
        - ./cert:/usr/src/app/cert
        image: malotian/passport-saml-nodejs-sample:latest
        networks:
            - example.com
        hostname: saml-sp
        domainname: iam.com
        extra_hosts:
        - "sp.iam.com:127.0.0.1"

networks:
    example.com:
       driver: bridge
       name: iam.com
