version: '3.5'
services:
    passport-saml-nodejs-proxy:
        environment:
        - HTTPS=true
        container_name: passport-saml-nodejs-proxy
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "443:3000"
        restart: always
        volumes:
        - ./cert:/usr/src/app/cert
        image: malotian/passport-saml-nodejs-proxy:latest
        networks:
            - docker.local
        hostname: saml-sp
        domainname: docker.local

    sample-webapp:
        container_name: sample-webapp
        build:
            context: sample-webapp
            dockerfile: Dockerfile
        ports:
        - "80:80"
        restart: always
        image: malotian/sample-webapp:latest
        networks:
            docker.local:
                aliases:
                    - cerpassrx-dev.azurewebsites.net
        hostname: sample-webapp
        domainname: docker.local

networks:
    docker.local:
       driver: bridge
       name: docker.local
