version: '3.5'
services:
    sp1:
        environment:
        - HTTPS=true
        - CONFIG_FILE=sp1.config.json
        container_name: sp1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "8443:3000"
        restart: always
        volumes:
        - ./cert:/usr/src/app/cert
        image: malotian/passport-saml-nodejs-proxy:latest
        networks:
            - docker.local
        hostname: sp1
        domainname: docker.local
    sp2:
        environment:
        - HTTPS=true
        - CONFIG_FILE=sp2.config.json
        container_name: sp2
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "9443:3000"
        restart: always
        volumes:
        - ./cert:/usr/src/app/cert
        image: malotian/passport-saml-nodejs-proxy:latest
        networks:
            - docker.local
        hostname: sp2
        domainname: docker.local        
    sample-webapp:
        container_name: sample-webapp
        build:
            context: sample-webapp
            dockerfile: Dockerfile
        ports:
        - "8080:80"
        restart: always
        image: malotian/sample-webapp:latest
        networks:
            docker.local:
                aliases:
                    - sample-webapp.docker.local
        hostname: sample-webapp
        domainname: docker.local

networks:
    docker.local:
       driver: bridge
       name: docker.local

