version: '3.5'
services:
    passport-saml-nodejs-proxy:
        container_name: passport-saml-nodejs-proxy
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "443:3000"
        restart: always
        volumes:
        - ./cert:/usr/src/app/cert
        image: malotian/passport-saml-nodejs-proxy:latest
        networks:
            - example.com
        hostname: saml-sp
        domainname: example.com
        extra_hosts:
        - "passport-saml-nodejs-proxy.example.com:127.0.0.1"

networks:
    example.com:
       driver: bridge
       name: example.com
